export class UsersData {
    constructor() {
        this.listSort = [
            {
                sortToken: "User-1",
                sortType: "ASC",
                propertyName: "userNameEn",
                sortNameCurrent: "Name Alphabetical Ascending",
                sortNameAr: "الأسم  أبجدي تصاعدي",
                sortNameEn: "Name Alphabetical Ascending",
                sortNameUnd: "الأسم  أبجدي تصاعدي",
            },
            {
                sortToken: "User-2",
                sortType: "DESC",
                propertyName: "userNameEn",
                sortNameCurrent: "Name Alphabetical Descending",
                sortNameAr: "الأسم  أبجدي تنازلي",
                sortNameEn: "Name Alphabetical Descending",
                sortNameUnd: "الأسم  أبجدي تنازلي",
            },
            {
                sortToken: "BaseEntityModel-2",
                sortType: "DESC",
                propertyName: "creationDateTime",
                sortNameCurrent: "creation Date Time descending",
                sortNameAr: "تاريخ و وقت الإنشاء تنازلي",
                sortNameEn: "creation Date Time descending",
                sortNameUnd: "تاريخ و وقت الإنشاء تنازلي",
            },
            {
                sortToken: "BaseEntityModel-1",
                sortType: "ASC",
                propertyName: "creationDateTime",
                sortNameCurrent: "creation Date Time ascending",
                sortNameAr: "تاريخ و وقت الإنشاء تصاعدي",
                sortNameEn: "creation Date Time ascending",
                sortNameUnd: "تاريخ و وقت الإنشاء تصاعدي",
            },
        ];
    }
}
export let Users = {
    status: 200,
    msg: "Students Data fetched the",
    executionTimeMilliseconds: 591.0,
    listSort: [
        {
            sortToken: "User-1",
            sortType: "ASC",
            propertyName: "userNameEn",
            sortNameCurrent: "Name Alphabetical Ascending",
            sortNameAr: "الأسم  أبجدي تصاعدي",
            sortNameEn: "Name Alphabetical Ascending",
            sortNameUnd: "الأسم  أبجدي تصاعدي",
        },
        {
            sortToken: "User-2",
            sortType: "DESC",
            propertyName: "userNameEn",
            sortNameCurrent: "Name Alphabetical Descending",
            sortNameAr: "الأسم  أبجدي تنازلي",
            sortNameEn: "Name Alphabetical Descending",
            sortNameUnd: "الأسم  أبجدي تنازلي",
        },
        {
            sortToken: "BaseEntityModel-2",
            sortType: "DESC",
            propertyName: "creationDateTime",
            sortNameCurrent: "creation Date Time descending",
            sortNameAr: "تاريخ و وقت الإنشاء تنازلي",
            sortNameEn: "creation Date Time descending",
            sortNameUnd: "تاريخ و وقت الإنشاء تنازلي",
        },
        {
            sortToken: "BaseEntityModel-1",
            sortType: "ASC",
            propertyName: "creationDateTime",
            sortNameCurrent: "creation Date Time ascending",
            sortNameAr: "تاريخ و وقت الإنشاء تصاعدي",
            sortNameEn: "creation Date Time ascending",
            sortNameUnd: "تاريخ و وقت الإنشاء تصاعدي",
        },
    ],
    activationStatistics: {
        totalCount: 5,
        totalActiveCount: 3,
        totalBlockedCount: 2,
        totalActivePercentage: 60.0,
        totalActivePercentageText: "60.0%",
        totalBlockedPercentage: 40.0,
        totalBlockedPercentageText: "40.0%",
    },
    pagination: {
        totalPages: 1,
        totalItems: 3,
        countItemsInPage: 3,
        selfPage: 1,
        firstPage: 1,
        prevPage: 1,
        nextPage: 1,
        lastPage: 1,
    },
};
